### ISSUE TITLE
ElasticGNN cached issue

### ISSUE THREAD

**Issue by ntgbaoo** [EdisonLeeeee/GraphWar#14]
Hi!

Thanks for a very nice package. I think there is an issue with[`def cached_clear(self)` function](https://github.com/EdisonLeeeee/GreatX/blob/master/greatx/nn/models/supervised/elastic_gnn.py#L93) inside ElasticGNN.
This code `self.prop._cached_inc = None`, I believe, doesn't reset anything actually because there is no attribute called `_cached_inc` in [`ElasticConv`](https://github.com/EdisonLeeeee/GreatX/blob/master/greatx/nn/layers/elastic_conv.py#L62). I think the cached data is stored in `_cached` instead, so it need to be set to `None` if we want to clear the cache.

I've already tried to run and initialize `ElasticGNN` with `cached = False` to avoid the model using cached `adj` in inference time to test the performance in evasion setting. But I got the error coming from `self.init_z` is not initialized yet. After reading your implementation, I noticed that `self.init_z` is never initialized if `self.cached = False`. In order words, `self.cached` must be set to `True` all the time?

Thanks

**Comment by EdisonLeeeee** [comment]
Hi @benjaminnNgo 

Thanks for reporting! Just fixed in master via https://github.com/EdisonLeeeee/GreatX/commit/2d02437946921a7b91011f284c50bed227587921
